use serde::{Deserialize, Serialize};
use strum::{Display, EnumString};
use tokio_postgres::types::FromSql;

#[derive(Debug, Serialize, Deserialize, PartialEq, Eq, Hash, Clone, EnumString, Display)]
#[serde(rename_all = "lowercase")]
#[strum(serialize_all = "lowercase")]
pub enum FileTypes {
    Png,
    Jpg,
    Jpeg,
    Webp,
    Gif,
    Svg,
    Pdf,
    Doc,
    Docx,
    Txt,
    Xls,
    Xlsx,
    Mp3,
    Wav,
    Ogg,
    Mp4,
    Mov,
    Avi,
    Webm,
    Zip,
    Rar,
    Json,
    Csv,
    Md,
    Mdx,
    Xml,
    Yml,
    Sql,
    Bmp,
    Heic,
    Raw,
    Tiff,
    Psd,
    Aac,
    M4p,
    Js,
    Jsx,
    Tsx,
    Css,
    Scss,
    Sass,
    Py,
    Rb,
    Php,
    Sh,
    Java,
    Cs,
    Html,
    Ttf,
    Otf,
    Woff,
    Exe,
    Other(String),
}

impl FileTypes {
    pub fn content_type(&self) -> &'static str {
        match self {
            FileTypes::Png => "image/png",
            FileTypes::Jpg | FileTypes::Jpeg => "image/jpeg",
            FileTypes::Webp => "image/webp",
            FileTypes::Gif => "image/gif",
            FileTypes::Svg => "image/svg+xml",
            FileTypes::Pdf => "application/pdf",
            FileTypes::Doc => "application/msword",
            FileTypes::Docx => {
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            }
            FileTypes::Txt => "text/plain",
            FileTypes::Xls => "application/vnd.ms-excel",
            FileTypes::Xlsx => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            FileTypes::Mp3 => "audio/mpeg",
            FileTypes::Wav => "audio/wav",
            FileTypes::Ogg => "audio/ogg",
            FileTypes::Mp4 => "video/mp4",
            FileTypes::Mov => "video/quicktime",
            FileTypes::Avi => "video/x-msvideo",
            FileTypes::Webm => "video/webm",
            FileTypes::Zip => "application/zip",
            FileTypes::Rar => "application/vnd.rar",
            FileTypes::Json => "application/json",
            FileTypes::Csv => "text/csv",
            FileTypes::Md => "text/markdown",
            FileTypes::Mdx => "text/markdown",
            FileTypes::Xml => "application/xml",
            FileTypes::Yml => "application/x-yaml",
            FileTypes::Sql => "application/sql",
            FileTypes::Bmp => "image/bmp",
            FileTypes::Heic => "image/heic",
            FileTypes::Raw => "image/x-raw",
            FileTypes::Tiff => "image/tiff",
            FileTypes::Psd => "image/vnd.adobe.photoshop",
            FileTypes::Aac => "audio/aac",
            FileTypes::M4p => "audio/mp4",
            FileTypes::Js => "application/javascript",
            FileTypes::Jsx => "text/jsx",
            FileTypes::Tsx => "text/tsx",
            FileTypes::Css => "text/css",
            FileTypes::Scss => "text/x-scss",
            FileTypes::Sass => "text/x-sass",
            FileTypes::Py => "text/x-python",
            FileTypes::Rb => "text/x-ruby",
            FileTypes::Php => "application/x-httpd-php",
            FileTypes::Sh => "application/x-sh",
            FileTypes::Java => "text/x-java-source",
            FileTypes::Cs => "text/x-csharp",
            FileTypes::Html => "text/html",
            FileTypes::Ttf => "font/ttf",
            FileTypes::Otf => "font/otf",
            FileTypes::Woff => "font/woff",
            FileTypes::Exe => "application/vnd.microsoft.portable-executable",
            FileTypes::Other(_) => "application/octet-stream",
        }
    }
}

impl<'a> FromSql<'a> for FileTypes {
    fn from_sql(
        _ty: &tokio_postgres::types::Type,
        raw: &'a [u8],
    ) -> Result<Self, Box<dyn std::error::Error + Sync + Send>> {
        match std::str::from_utf8(raw)?.to_lowercase().as_str() {
            "png" => Ok(FileTypes::Png),
            "jpg" => Ok(FileTypes::Jpg),
            "jpeg" => Ok(FileTypes::Jpeg),
            "webp" => Ok(FileTypes::Webp),
            "gif" => Ok(FileTypes::Gif),
            "svg" => Ok(FileTypes::Svg),
            "pdf" => Ok(FileTypes::Pdf),
            "doc" => Ok(FileTypes::Doc),
            "docx" => Ok(FileTypes::Docx),
            "txt" => Ok(FileTypes::Txt),
            "xls" => Ok(FileTypes::Xls),
            "xlsx" => Ok(FileTypes::Xlsx),
            "mp3" => Ok(FileTypes::Mp3),
            "wav" => Ok(FileTypes::Wav),
            "ogg" => Ok(FileTypes::Ogg),
            "mp4" => Ok(FileTypes::Mp4),
            "mov" => Ok(FileTypes::Mov),
            "avi" => Ok(FileTypes::Avi),
            "webm" => Ok(FileTypes::Webm),
            "zip" => Ok(FileTypes::Zip),
            "rar" => Ok(FileTypes::Rar),
            "json" => Ok(FileTypes::Json),
            "csv" => Ok(FileTypes::Csv),
            "md" => Ok(FileTypes::Md),
            "mdx" => Ok(FileTypes::Mdx),
            "xml" => Ok(FileTypes::Xml),
            "yml" | "yaml" => Ok(FileTypes::Yml),
            "sql" => Ok(FileTypes::Sql),
            "bmp" => Ok(FileTypes::Bmp),
            "heic" => Ok(FileTypes::Heic),
            "raw" => Ok(FileTypes::Raw),
            "tiff" | "tif" => Ok(FileTypes::Tiff),
            "psd" => Ok(FileTypes::Psd),
            "aac" => Ok(FileTypes::Aac),
            "m4p" => Ok(FileTypes::M4p),
            "js" => Ok(FileTypes::Js),
            "jsx" => Ok(FileTypes::Jsx),
            "tsx" => Ok(FileTypes::Tsx),
            "css" => Ok(FileTypes::Css),
            "scss" => Ok(FileTypes::Scss),
            "sass" => Ok(FileTypes::Sass),
            "py" => Ok(FileTypes::Py),
            "rb" => Ok(FileTypes::Rb),
            "php" => Ok(FileTypes::Php),
            "sh" => Ok(FileTypes::Sh),
            "java" => Ok(FileTypes::Java),
            "cs" => Ok(FileTypes::Cs),
            "html" => Ok(FileTypes::Html),
            "ttf" => Ok(FileTypes::Ttf),
            "otf" => Ok(FileTypes::Otf),
            "woff" => Ok(FileTypes::Woff),
            "exe" => Ok(FileTypes::Exe),
            other => Ok(FileTypes::Other(other.to_string())),
        }
    }

    fn accepts(ty: &tokio_postgres::types::Type) -> bool {
        ty == &tokio_postgres::types::Type::TEXT
    }
}
