export const Icons = {
  aac: "bi:filetype-aac",
  add: "ph:plus" as const,
  ai: "bi:filetype-ai",
  arrowDown: "lucide:chevron-down" as const,
  arrowLeft: "lucide:chevron-left" as const,
  arrowRight: "lucide:chevron-right" as const,
  arrowUp: "lucide:chevron-up" as const,
  bmp: "bi:filetype-bmp",
  cs: "bi:filetype-cs",
  css: "bi:filetype-css",
  csv: "bi:filetype-csv",
  dashboard: "clarity:dashboard-line" as const,
  expand: "ci:expand" as const,
  grid: "cuida:grid-outline" as const,
  doc: "bi:filetype-docx" as const,
  docx: "bi:filetype-docx" as const,
  exe: "bi:filetype-exe",
  gif: "bi:filetype-gif",
  heic: "bi:filetype-heic",
  html: "bi:filetype-html",
  java: "bi:filetype-java",
  jpg: "bi:filetype-jpg",
  js: "bi:filetype-js",
  json: "bi:filetype-json",
  jsx: "bi:filetype-jsx",
  key: "bi:filetype-key",
  list: "lucide:list" as const,
  m4p: "bi:filetype-m4p",
  md: "bi:filetype-md",
  mdx: "bi:filetype-mdx",
  mov: "bi:filetype-mov",
  mp3: "bi:filetype-mp3",
  mp4: "bi:filetype-mp4",
  notification: "ph:bell" as const,
  otf: "bi:filetype-otf",
  pdf: "bi:filetype-pdf" as const,
  php: "bi:filetype-php",
  png: "bi:filetype-png",
  ppt: "bi:filetype-ppt",
  pptx: "bi:filetype-pptx",
  psd: "bi:filetype-psd",
  py: "bi:filetype-py",
  raw: "bi:filetype-raw",
  rb: "bi:filetype-rb",
  sass: "bi:filetype-sass",
  scss: "bi:filetype-scss",
  search: "tabler:search" as const,
  sh: "bi:filetype-sh",
  sql: "bi:filetype-sql",
  svg: "bi:filetype-svg",
  sort: "system-uicons:sort",
  tasks: "material-symbols:task-alt-rounded" as const,
  tiff: "bi:filetype-tiff",
  tsx: "bi:filetype-tsx",
  ttf: "bi:filetype-ttf",
  txt: "bi:filetype-txt",
  upload: "tabler:upload" as const,
  user: "lucide:user" as const,
  wav: "bi:filetype-wav",
  woff: "bi:filetype-woff",
  xls: "bi:filetype-xls",
  xlsx: "bi:filetype-xlsx" as const,
  xml: "bi:filetype-xml",
  yml: "bi:filetype-yml",
};

export type AvailableIcons = (typeof Icons)[keyof typeof Icons];
